services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mvv081105
      MYSQL_DATABASE: epidem_monitoring
     
    ports:
      - "3307:3306"
    networks:
      - monitoring_network
    # ДОДАНО: Перевірка, чи база даних готова приймати з'єднання
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=epidem_monitoring
      - DB_USER=root
      - DB_PASSWORD=mvv081105
      - DB_HOST=db
      - DB_PORT=3306
    # ОНОВЛЕНО: Тепер web чекає, поки db стане "здоровим"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring_network

volumes:
  mysql_data:

networks:
  monitoring_network:
    driver: bridge